INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u1','regisastra@dio.com','pbkdf2$PINeeGwCdHfV396mymZrHw==$uvBYkGAeIwBQdriKQZwrGj/SG11Ubw7+zevF0G3BaO0=','Regis Astra Dio','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$PINeeGwCdHfV396mymZrHw==$uvBYkGAeIwBQdriKQZwrGj/SG11Ubw7+zevF0G3BaO0=', name='Regis Astra Dio', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u2','regisastra@bara.com','pbkdf2$KbGDRPREAzvFLdLA+N9gwQ==$dEttquXYNE5Xlu7jmk0ncVyLafbm97sdl8jhxvNruwA=','Regis Astra Bara','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$KbGDRPREAzvFLdLA+N9gwQ==$dEttquXYNE5Xlu7jmk0ncVyLafbm97sdl8jhxvNruwA=', name='Regis Astra Bara', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u3','regisastra@hafizh.com','pbkdf2$dT5qD+nGaWJscFc/QgJaDw==$Z7D7CknZ/FMFssFFEtTtqjxVill6JG1gRu9ywTF/vuc=','Regis Astra Hafizh','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$dT5qD+nGaWJscFc/QgJaDw==$Z7D7CknZ/FMFssFFEtTtqjxVill6JG1gRu9ywTF/vuc=', name='Regis Astra Hafizh', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u4','regisastri@aspiratu.com','pbkdf2$+pgxjt6sNBE7Qy9K0ZlrBQ==$76sciIQuRdnUZ53kPrC6B47Kxhwzlb8AI5gKAHCy6Mw=','Regis Astri Aspiratu','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$+pgxjt6sNBE7Qy9K0ZlrBQ==$76sciIQuRdnUZ53kPrC6B47Kxhwzlb8AI5gKAHCy6Mw=', name='Regis Astri Aspiratu', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u5','regisastri@raudah.com','pbkdf2$EXyFsE0iQhcEVQR8uehikg==$Rd6+pdWlzjdwF5Vw73IskXGYSPtyEAbxExQFNcgFVNU=','Regis Astri Raudah','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$EXyFsE0iQhcEVQR8uehikg==$Rd6+pdWlzjdwF5Vw73IskXGYSPtyEAbxExQFNcgFVNU=', name='Regis Astri Raudah', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u6','regisastri@nadia.com','pbkdf2$RU9xC684tzmriHvzTmg36w==$aBcNjTaJJ+KsfRz/zonYI2tA1DOcHZr9d08zPCg9mbs=','Regis Astri Nadia','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$RU9xC684tzmriHvzTmg36w==$aBcNjTaJJ+KsfRz/zonYI2tA1DOcHZr9d08zPCg9mbs=', name='Regis Astri Nadia', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u7','regisastri@haura.com','pbkdf2$ZlMS6ovQ56ZF7ZzViSm6+A==$f20x23VKnlpDPIfFzLBJcX9qxHMs8cRWW7wRsykiSvE=','Regis Astri Haura','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$ZlMS6ovQ56ZF7ZzViSm6+A==$f20x23VKnlpDPIfFzLBJcX9qxHMs8cRWW7wRsykiSvE=', name='Regis Astri Haura', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('u8','regis@asrama.com','pbkdf2$22KcXlpX0v0Hv5nzpeWjWA==$LtHk+aZ/HM4ydBDx8lpUZhZRx0/ZSwBMLm5XdLHuk0c=','Regis Asrama','staff') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$22KcXlpX0v0Hv5nzpeWjWA==$LtHk+aZ/HM4ydBDx8lpUZhZRx0/ZSwBMLm5XdLHuk0c=', name='Regis Asrama', role='staff';
INSERT INTO admins(id,username,password_hash,name,role) VALUES ('admin1','regis@admin.com','pbkdf2$V2ny/BWoor4CQr4V4LhPfg==$Ax3GJQ++yMLqzBCLN38CPVbiAK9YRcOZGghlNKNP02c=','Super Admin','super') ON CONFLICT(username) DO UPDATE SET password_hash='pbkdf2$V2ny/BWoor4CQr4V4LhPfg==$Ax3GJQ++yMLqzBCLN38CPVbiAK9YRcOZGghlNKNP02c=', name='Super Admin', role='super';
